"""
FastAPI application — single POST /chat endpoint.

Session state is held in a server-side dict keyed by session_id.
The session_id is generated by the frontend on first load and sent
with every request.

Request body:
    {
        "session_id":           str,
        "user_input":           str,
        "conversation_history": list[{"role": str, "content": str}]
    }

Response body:
    {
        "response":      str,
        "tone":          str,
        "topic":         str,
        "stage":         str,
        "is_terminal":   bool,
        "terminal_type": str | null
    }
"""

import os
from contextlib import asynccontextmanager

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

# Load .env before importing anything that reads OPENAI_API_KEY
load_dotenv()

from Backend.classifier import classify          # noqa: E402
from Backend.generator import generate           # noqa: E402
from Backend.retriever import retrieve           # noqa: E402
from Backend.state_machine import State          # noqa: E402

# ---------------------------------------------------------------------------
# Session store  (in-memory — sufficient for single-user / demo use)
# ---------------------------------------------------------------------------

_sessions: dict[str, State] = {}


def _get_or_create_state(session_id: str) -> State:
    if session_id not in _sessions:
        _sessions[session_id] = State()
    return _sessions[session_id]


# ---------------------------------------------------------------------------
# App setup
# ---------------------------------------------------------------------------

@asynccontextmanager
async def lifespan(app: FastAPI):
    # Warm up the retriever (loads ChromaDB + sentence-transformer model)
    # so the first request isn't slow.
    try:
        retrieve("virtue", "eudaimonia", n_results=1)
        print("Retriever warmed up.")
    except Exception as exc:
        print(f"Retriever warm-up skipped (loader not yet run?): {exc}")
    yield


app = FastAPI(title="Aristotle Philosophy Chatbot", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["POST", "GET"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# Request / response models
# ---------------------------------------------------------------------------

class Turn(BaseModel):
    role: str
    content: str


class ChatRequest(BaseModel):
    session_id: str = Field(..., min_length=1)
    user_input: str = Field(..., min_length=1)
    conversation_history: list[Turn] = Field(default_factory=list)


class ChatResponse(BaseModel):
    response: str
    tone: str
    topic: str
    stage: str
    is_terminal: bool
    terminal_type: str | None


# ---------------------------------------------------------------------------
# /chat endpoint
# ---------------------------------------------------------------------------

@app.post("/chat", response_model=ChatResponse)
async def chat(req: ChatRequest) -> ChatResponse:
    state = _get_or_create_state(req.session_id)

    # Already in a terminal state — return a canned notice rather than
    # burning more LLM tokens on a closed conversation.
    if state.is_terminal:
        msg = (
            "Our dialogue has reached its end. Refresh the page to begin anew."
            if state.terminal_type == "end"
            else "You have been dismissed. Reflect, and return when you are ready."
        )
        return ChatResponse(
            response=msg,
            tone=state.tone,
            topic=state.topic,
            stage=state.stage,
            is_terminal=True,
            terminal_type=state.terminal_type,
        )

    # --- Step 1: classify ---
    last_aristotle = next(
        (t.content for t in reversed(req.conversation_history) if t.role == "assistant"),
        "",
    )
    try:
        classification = classify(req.user_input, last_aristotle_message=last_aristotle)
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"Classifier error: {exc}")

    # --- Step 2: transition state ---
    state.transition(classification)

    # --- Step 3: retrieve RAG context ---
    try:
        rag_chunks = retrieve(req.user_input, state.topic)
    except Exception:
        # Gracefully degrade — proceed without RAG rather than failing the turn
        rag_chunks = []

    # --- Step 4: generate response ---
    history = [t.model_dump() for t in req.conversation_history]
    try:
        response_text = generate(
            state=state,
            classification=classification,
            rag_chunks=rag_chunks,
            conversation_history=history,
            student_input=req.user_input,
        )
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"Generator error: {exc}")

    return ChatResponse(
        response=response_text,
        tone=state.tone,
        topic=state.topic,
        stage=state.stage,
        is_terminal=state.is_terminal,
        terminal_type=state.terminal_type,
    )


# ---------------------------------------------------------------------------
# Health check
# ---------------------------------------------------------------------------

@app.get("/health")
async def health():
    return {"status": "ok", "sessions": len(_sessions)}


# ---------------------------------------------------------------------------
# Static file mounts — must come AFTER all API routes so POST /chat is not
# intercepted by the catch-all "/" mount.
# ---------------------------------------------------------------------------

_frontend_dir = os.path.join(os.path.dirname(__file__), "..", "frontend")
_images_dir   = os.path.join(os.path.dirname(__file__), "..", "images")
if os.path.isdir(_images_dir):
    app.mount("/images", StaticFiles(directory=_images_dir), name="images")
if os.path.isdir(_frontend_dir):
    app.mount("/", StaticFiles(directory=_frontend_dir, html=True), name="frontend")
